services:
  app:
    build:
      dockerfile: Docker-build/app/Dockerfile
      context: ./
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:qwer@pg:5432/school
    ports:
      - "5353:8000"
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./my_school
          target: /app
        - action: rebuild
          path: ./poetry.lock

  pg:
    image: postgres
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwer
      PGDATA: /var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${APP_CONFIG__REDIS__PASSWORD}
      - REDIS_USER=${APP_CONFIG__REDIS__USER}
      - REDIS_USER_PASSWORD=${APP_CONFIG__REDIS__USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD","ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  pgdata:
  redis_data: