services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:qwer@pg:5432/school
    ports:
      - "5353:8000"

  pg:
    image: postgres
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwer
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"