"""create school subject table

Revision ID: 9bcd710ac47c
Revises: 5678ef54819f
Create Date: 2025-08-02 14:34:52.918079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bcd710ac47c"
down_revision: Union[str, Sequence[str], None] = "5678ef54819f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schoolsubjects",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("school_assessment", sa.Integer(), nullable=False),
        sa.Column("id_student", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_student"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "students_object_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("schoolsubject_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["schoolsubject_id"],
            ["schoolsubjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id", "student_id", "schoolsubject_id"),
        sa.UniqueConstraint(
            "student_id", "schoolsubject_id", name="uniq_student_subject"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("students_object_table")
    op.drop_table("schoolsubjects")
    # ### end Alembic commands ###
