"""create table day shool and corrected subject

Revision ID: a03d9f250b1c
Revises: 9bcd710ac47c
Create Date: 2025-08-03 13:05:37.018890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a03d9f250b1c"
down_revision: Union[str, Sequence[str], None] = "9bcd710ac47c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dayschools",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("school_assessment", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["schoolsubjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        op.f("schoolsubjects_id_student_fkey"),
        "schoolsubjects",
        type_="foreignkey",
    )
    op.drop_column("schoolsubjects", "id_student")
    op.drop_column("schoolsubjects", "school_assessment")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schoolsubjects",
        sa.Column(
            "school_assessment",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "schoolsubjects",
        sa.Column(
            "id_student", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("schoolsubjects_id_student_fkey"),
        "schoolsubjects",
        "students",
        ["id_student"],
        ["id"],
    )
    op.drop_table("dayschools")
    # ### end Alembic commands ###
